# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_require 'dotenv'

before_all do
  Dotenv.overload '.env'
end

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "SerialLuncher.xcodeproj")
    build_app(workspace: "SerialLuncher.xcworkspace", scheme: "SerialLuncher", xcargs: "-allowProvisioningUpdates")
    upload_to_app_store
    notify_after_build(platform: "iOS", release_type: "App Store", version: get_version_number(xcodeproj: "SerialLuncher.xcodeproj"), app_name: "SerialLuncher")
  end

  desc "Push a new release build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "SerialLuncher.xcodeproj")
    build_app(workspace: "SerialLuncher.xcworkspace", scheme: "SerialLuncher", xcargs: "-allowProvisioningUpdates")
    upload_to_testflight
    notify_after_build(platform: "iOS", release_type: "TestFlight", version: get_version_number(xcodeproj: "SerialLuncher.xcodeproj"), app_name: "SerialLuncher")
  end

  lane :notify_after_build do |options|
    discord_notifier(
      webhook_url:"https://discord.com/api/webhooks/1034458031867580466/wee_AWeZRKPnzSoY8FM32Vo9gIJctmdN8yGe3yjeGVIIrNBOuk-s_EOF0sFYetyGPy4i",
      title: "Fastlane iOS — Build #{options[:release_type]}",
      description: "Le build #{options[:app_name]} (#{options[:version]}) a été envoyé avec succès ! Il sera disponible dans quelques minutes.",
    )
  end
end
