# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(
      task: "assemble",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => "#{ENV['ANDROID_KEYSTORE']}",
        "android.injected.signing.store.password" => "#{ENV['ANDROID_PASSWORD']}",
        "android.injected.signing.key.alias" => "#{ENV['ANDROID_ALIAS']}",
        "android.injected.signing.key.password" => "#{ENV['ANDROID_ALIAS_PASSWORD']}",
        "android.injected.version.code" => "#{ENV['ANDROID_CODE']}",
        "android.injected.version.name" => "#{ENV['ANDROID_VERSION']}"
      }
    )
    upload_to_play_store
  end
end
